name: Deploy Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          protocol: ftp
          port: 21
          local-dir: ./
          remote-dir: /home/clients/56d3c6336f99048d3d9d7cdf4bbc2288/sites/staging.eigentumer-check.ch/
